#!/bin/bash

rm b_h*.root 
rm b_l*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

for i in {1..20}; do
    ../build/crdirc -r 0 -seed $tseed$i -study 500 -a 90 -o b_h$i.root -e 8000000 -b 1 > b_l$i.log &
done


sleep 1

while : 
do
    activth=$(ps aux | grep "[c]rd" | grep "b_h" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active prt simulations " 
    if [ "$activth" -eq 0 ]; then 
	break  
    fi
    sleep 2
done

sleep 2

hadd -f hits_90n.root b_h*.root
